export const allPets = [
  { name: "Buddy", type: "Dogs", image: "/dog1.jpg" },
  { name: "Max", type: "Dogs", image: "/dog2.jpg" },
  { name: "Bella", type: "Dogs", image: "/dog3.jpg" },
  { name: "Charlie", type: "Dogs", image: "/dog4.jpg" },
  { name: "Lucy", type: "Dogs", image: "/dog5.jpg" },
  { name: "Daisy", type: "Dogs", image: "/dog6.jpg" },
  { name: "Bailey", type: "Dogs", image: "/dog7.jpg" },
  { name: "Lola", type: "Dogs", image: "/dog8.jpg" },
  { name: "Molly", type: "Dogs", image: "/dog9.jpg" },
  { name: "Rocky", type: "Dogs", image: "/dog10.jpg" },
  
  { name: "Mittens", type: "Cats", image: "/cat1.jpg" },
  { name: "Whiskers", type: "Cats", image: "/cat2.jpg" },
  { name: "Shadow", type: "Cats", image: "/cat3.jpg" },
  { name: "Smokey", type: "Cats", image: "/cat4.jpg" },
  { name: "Luna", type: "Cats", image: "/cat5.jpg" },
  { name: "Simba", type: "Cats", image: "/cat6.jpg" },
  { name: "Chloe", type: "Cats", image: "/cat7.jpg" },
  { name: "Milo", type: "Cats", image: "/cat8.jpg" },
  { name: "Cleo", type: "Cats", image: "/cat9.jpg" },
  { name: "Leo", type: "Cats", image: "/cat10.jpg" },

  { name: "Tweety", type: "Birds", image: "/bird1.jpg" },
  { name: "Kiwi", type: "Birds", image: "/bird2.jpg" },
  { name: "Sunny", type: "Birds", image: "/bird3.jpg" },
  { name: "Coco", type: "Birds", image: "/bird4.jpg" },
  { name: "Sky", type: "Birds", image: "/bird5.jpg" },
  { name: "Rio", type: "Birds", image: "/bird6.jpg" },
  { name: "Angel", type: "Birds", image: "/bird7.jpg" },
  { name: "Mango", type: "Birds", image: "/bird8.jpg" },
  { name: "Peach", type: "Birds", image: "/bird9.jpg" },
  { name: "Blue", type: "Birds", image: "/bird10.jpg" },

  { name: "Nemo", type: "Fish", image: "/fish1.jpg" },
  { name: "Bubbles", type: "Fish", image: "/fish2.jpg" },
  { name: "Goldie", type: "Fish", image: "/fish3.jpg" },
  { name: "Finley", type: "Fish", image: "/fish4.jpg" },
  { name: "Splash", type: "Fish", image: "/fish5.jpg" },
  { name: "Coral", type: "Fish", image: "/fish6.jpg" },
  { name: "Shadow", type: "Fish", image: "/fish7.jpg" },
  { name: "Sunny", type: "Fish", image: "/fish8.jpg" },
  { name: "Storm", type: "Fish", image: "/fish9.jpg" },
  { name: "Flash", type: "Fish", image: "/fish10.jpg" },

  { name: "Thumper", type: "Rabbits", image: "/rabbit1.jpg" },
  { name: "Cinnamon", type: "Rabbits", image: "/rabbit2.jpg" },
  { name: "Snowball", type: "Rabbits", image: "/rabbit3.jpg" },
  { name: "Hazel", type: "Rabbits", image: "/rabbit4.jpg" },
  { name: "Coco", type: "Rabbits", image: "/rabbit5.jpg" },
  { name: "Pepper", type: "Rabbits", image: "/rabbit6.jpg" },
  { name: "Misty", type: "Rabbits", image: "/rabbit7.jpg" },
  { name: "Fudge", type: "Rabbits", image: "/rabbit8.jpg" },
  { name: "Cookie", type: "Rabbits", image: "/rabbit9.jpg" },
  { name: "Marshmallow", type: "Rabbits", image: "/rabbit10.jpg" },

  { name: "Iggy", type: "Reptiles", image: "/reptile1.jpg" },
  { name: "Spike", type: "Reptiles", image: "/reptile2.jpg" },
  { name: "Rango", type: "Reptiles", image: "/reptile3.jpg" },
  { name: "Draco", type: "Reptiles", image: "/reptile4.jpg" },
  { name: "Echo", type: "Reptiles", image: "/reptile5.jpg" },
  { name: "Jade", type: "Reptiles", image: "/reptile6.jpg" },
  { name: "Basil", type: "Reptiles", image: "/reptile7.jpg" },
  { name: "Tango", type: "Reptiles", image: "/reptile8.jpg" },
  { name: "Mojo", type: "Reptiles", image: "/reptile9.jpg" },
  { name: "Sage", type: "Reptiles", image: "/reptile10.jpg" },

  { name: "Nibbles", type: "Small Pets", image: "/smallpet1.jpg" },
  { name: "Peanut", type: "Small Pets", image: "/smallpet2.jpg" },
  { name: "Pumpkin", type: "Small Pets", image: "/smallpet3.jpg" },
  { name: "Biscuit", type: "Small Pets", image: "/smallpet4.jpg" },
  { name: "Popcorn", type: "Small Pets", image: "/smallpet5.jpg" },
  { name: "Nutmeg", type: "Small Pets", image: "/smallpet6.jpg" },
  { name: "Waffles", type: "Small Pets", image: "/smallpet7.jpg" },
  { name: "Muffin", type: "Small Pets", image: "/smallpet8.jpg" },
  { name: "Pudding", type: "Small Pets", image: "/smallpet9.jpg" },
  { name: "Truffle", type: "Small Pets", image: "/smallpet10.jpg" },

  { name: "Spirit", type: "Horses", image: "/horse1.jpg" },
  { name: "Blaze", type: "Horses", image: "/horse2.jpg" },
  { name: "Star", type: "Horses", image: "/horse3.jpg" },
  { name: "Storm", type: "Horses", image: "/horse4.jpg" },
  { name: "Majesty", type: "Horses", image: "/horse5.jpg" },
  { name: "Willow", type: "Horses", image: "/horse6.jpg" },
  { name: "Sugar", type: "Horses", image: "/horse7.jpg" },
  { name: "Sapphire", type: "Horses", image: "/horse8.jpg" },
  { name: "Jet", type: "Horses", image: "/horse9.jpg" },
  { name: "Midnight", type: "Horses", image: "/horse10.jpg" },

  { name: "Mystery", type: "Others", image: "/other1.jpg" },
  { name: "Echo", type: "Others", image: "/other2.jpg" },
  { name: "Pixie", type: "Others", image: "/other3.jpg" },
  { name: "Nova", type: "Others", image: "/other4.jpg" },
  { name: "Zephyr", type: "Others", image: "/other5.jpg" },
  { name: "Orion", type: "Others", image: "/other6.jpg" },
  { name: "Sable", type: "Others", image: "/other7.jpg" },
  { name: "Onyx", type: "Others", image: "/other8.jpg" },
  { name: "Ember", type: "Others", image: "/other9.jpg" },
  { name: "Galaxy", type: "Others", image: "/other10.jpg" },
];
